---
layout: post
title: "解决用try-except-捕获assert函数产生的AssertionError异常时,导致断言失败的用例在测试报告中通过的问题..."
date: 2024-12-12 23:32:42 +0800
description: "　　在使用Python3做自动化测试过程中可能会遇到,assert函数不加try except，就可"
keywords: "try assert断言失败生成测试报告"
categories: ["未分类"]
tags: ["Python", "Java", "C"]
artid: "93280036"
image:
  path: https://api.vvhan.com/api/bing?rand=sj&artid=93280036
  alt: "解决用try-except-捕获assert函数产生的AssertionError异常时,导致断言失败的用例在测试报告中通过的问题..."
render_with_liquid: false
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     解决用try except 捕获assert函数产生的AssertionError异常时,导致断言失败的用例在测试报告中通过的问题...
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="htmledit_views" id="content_views">
    <div class="blogpost-body" id="cnblogs_post_body">
     <p class="QuestionHeader-title">
      在使用Python3做自动化测试过程中可能会遇到,assert函数不加try  except，就可以正常在报告里体现用例不通过，加上变成通过。
     </p>
     <p class="QuestionHeader-title">
      这是因为在使用try except 时,捕获了assert函数产生的AssertionError异常,导致异常没有上抛,这时只需要在后面加上 raise 就可以再次把它抛出。
     </p>
     <div class="cnblogs_code">
      <pre>        <span style="color:#0000ff;">try</span><span style="color:#000000;">:</span><span style="color:#008000;">#</span><span style="color:#008000;"> 找到输入框并输入测试数据</span>
            self.driver.find_element_by_id(<span style="color:#800000;">"</span><span style="color:#800000;">kw</span><span style="color:#800000;">"</span><span style="color:#000000;">).send_keys(testdata)
            </span><span style="color:#008000;">#</span><span style="color:#008000;"> 找到搜索按钮,并单击</span>
            self.driver.find_element_by_id(<span style="color:#800000;">"</span><span style="color:#800000;">su</span><span style="color:#800000;">"</span><span style="color:#000000;">).click()
            time.sleep(</span>3<span style="color:#000000;">)
            </span><span style="color:#008000;">#</span><span style="color:#008000;"> 断言期望结果中是否出现页面源代码中</span>
<span style="color:#000000;">            self.assertIn(expectdata,self.driver.page_source)
            time.sleep(</span>3<span style="color:#000000;">)
      </span><span style="color:#0000ff;">except</span><span style="color:#000000;"> AssertionError as e:
            logger.info(u</span><span style="color:#800000;">"</span><span style="color:#800000;">搜索\"%s\",期望\"%s\"失败</span><span style="color:#800000;">"</span> %<span style="color:#000000;"> (testdata, expectdata))
            </span><span style="color:#0000ff;">raise </span>
        <span style="color:#0000ff;">else</span><span style="color:#000000;">:
            logger.info(u</span><span style="color:#800000;">"</span><span style="color:#800000;">搜索\"%s\",期望\"%s\"通过</span><span style="color:#800000;">"</span>%(testdata,expectdata))</pre>
     </div>
     <p>
     </p>
    </div>
    <p>
     转载于:https://www.cnblogs.com/fanjc/p/10072556.html
    </p>
   </div>
  </div>
  <div id="recommendDown">
  </div>
 </article>
 <p alt="68747470733a2f2f626c6f67:2e6373646e2e6e65742f77656978696e5f3333373031323531:2f61727469636c652f64657461696c732f3933323830303336" class_="artid" style="display:none">
 </p>
</div>
