---
arturl_encode: "68747470733a:2f2f626c6f672e6373646e2e6e65742f67756968756135352f:61727469636c652f64657461696c732f313135353538363837"
layout: post
title: "解决启动Hive出现Exception-in-thread-main-java.lang.RuntimeException-org.apache.hadoop.hive.ql.metadata"
date: 2022-12-28 17:41:53 +0800
description: "在启动Hive时出现如下错误：Logging initialized using configura"
keywords: 'exception in thread "main" java.lang.runtimeexception: org.apache.hadoop.hiv'
categories: ['未分类']
tags: ['无标签']
artid: "115558687"
image:
  path: https://api.vvhan.com/api/bing?rand=sj&artid=115558687
  alt: "解决启动Hive出现Exception-in-thread-main-java.lang.RuntimeException-org.apache.hadoop.hive.ql.metadata"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=115558687
featuredImagePreview: https://bing.ee123.net/img/rand?artid=115558687
---

# 解决：启动Hive出现Exception in thread “main“ java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata

## 在启动Hive时出现如下错误：

Logging initialized using configuration in jar:file:/usr/hive/apache-hive-2.1.1-bin/lib/hive-common-2.1.1.jar!/hive-log4j2.properties Async: true
  
**Exception in thread "main" java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient**
  
at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:591)
  
at org.apache.hadoop.hive.ql.session.SessionState.beginStart(SessionState.java:531)
  
at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:705)
  
at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:641)
  
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  
at java.lang.reflect.Method.invoke(Method.java:498)
  
at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
  
at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
  
**Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient**
  
at org.apache.hadoop.hive.ql.metadata.Hive.registerAllFunctionsOnce(Hive.java:226)
  
at org.apache.hadoop.hive.ql.metadata.Hive.<init>(Hive.java:366)
  
at org.apache.hadoop.hive.ql.metadata.Hive.create(Hive.java:310)
  
at org.apache.hadoop.hive.ql.metadata.Hive.getInternal(Hive.java:290)
  
at org.apache.hadoop.hive.ql.metadata.Hive.get(Hive.java:266)
  
at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:558)
  
... 9 more
  
**Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient**
  
at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1654)
  
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.<init>(RetryingMetaStoreClient.java:80)
  
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:130)
  
at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:101)
  
at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3367)
  
at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3406)
  
at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3386)
  
at org.apache.hadoop.hive.ql.metadata.Hive.getAllFunctions(Hive.java:3640)
  
at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:236)
  
at org.apache.hadoop.hive.ql.metadata.Hive.registerAllFunctionsOnce(Hive.java:221)
  
... 14 more
  
Caused by: java.lang.reflect.InvocationTargetException
  
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  
at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1652)
  
... 23 more
  
Caused by: javax.jdo.JDOFatalInternalException: Error creating transactional connection factory
  
NestedThrowables:
  
java.lang.reflect.InvocationTargetException
  
at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:671)
  
at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:834)
  
at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:338)
  
at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:217)
  
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  
at java.lang.reflect.Method.invoke(Method.java:498)
  
at javax.jdo.JDOHelper$16.run(JDOHelper.java:1965)
  
at java.security.AccessController.doPrivileged(Native Method)
  
at javax.jdo.JDOHelper.invoke(JDOHelper.java:1960)
  
at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1166)
  
at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:808)
  
at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:701)
  
at org.apache.hadoop.hive.metastore.ObjectStore.getPMF(ObjectStore.java:515)
  
at org.apache.hadoop.hive.metastore.ObjectStore.getPersistenceManager(ObjectStore.java:544)
  
at org.apache.hadoop.hive.metastore.ObjectStore.initializeHelper(ObjectStore.java:399)
  
at org.apache.hadoop.hive.metastore.ObjectStore.initialize(ObjectStore.java:336)
  
at org.apache.hadoop.hive.metastore.ObjectStore.setConf(ObjectStore.java:297)
  
at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:76)
  
at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)
  
at org.apache.hadoop.hive.metastore.RawStoreProxy.<init>(RawStoreProxy.java:58)
  
at org.apache.hadoop.hive.metastore.RawStoreProxy.getProxy(RawStoreProxy.java:67)
  
at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.newRawStore(HiveMetaStore.java:599)
  
at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:564)
  
at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:630)
  
at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:416)
  
at org.apache.hadoop.hive.metastore.RetryingHMSHandler.<init>(RetryingHMSHandler.java:78)
  
at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:84)
  
at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:6490)
  
at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:238)
  
at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:70)
  
... 28 more
  
Caused by: java.lang.reflect.InvocationTargetException
  
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  
at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
  
at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:330)
  
at org.datanucleus.store.AbstractStoreManager.registerConnectionFactory(AbstractStoreManager.java:203)
  
at org.datanucleus.store.AbstractStoreManager.<init>(AbstractStoreManager.java:162)
  
at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:284)
  
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  
at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
  
at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:301)
  
at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(NucleusContextHelper.java:133)
  
at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:420)
  
at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:821)
  
... 58 more
  
Caused by: org.datanucleus.exceptions.NucleusException: Attempt to invoke the "BONECP" plugin to create a ConnectionPool gave an error : The specified datastore driver ("com.mysql.jdbc.Driver") was not found in the CLASSPATH. Please check your CLASSPATH specification, and the name of the driver.
  
at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSources(ConnectionFactoryImpl.java:232)
  
at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSources(ConnectionFactoryImpl.java:117)
  
at org.datanucleus.store.rdbms.ConnectionFactoryImpl.<init>(ConnectionFactoryImpl.java:82)
  
... 76 more
  
Caused by: org.datanucleus.store.rdbms.connectionpool.DatastoreDriverNotFoundException: The specified datastore driver ("com.mysql.jdbc.Driver") was not found in the CLASSPATH. Please check your CLASSPATH specification, and the name of the driver.
  
at org.datanucleus.store.rdbms.connectionpool.AbstractConnectionPoolFactory.loadDriver(AbstractConnectionPoolFactory.java:58)
  
at org.datanucleus.store.rdbms.connectionpool.BoneCPConnectionPoolFactory.createConnectionPool(BoneCPConnectionPoolFactory.java:54)
  
at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSources(ConnectionFactoryImpl.java:213)
  
... 78 more

## 截图如下：

![](https://i-blog.csdnimg.cn/blog_migrate/7be88f5d29699e3509caa19156d635d9.png)

## 解决：

### 在部署mysql的那个节点使用命令格式化mysql服务，如下：

> **schematool -dbType mysql -initSchema**

![](https://i-blog.csdnimg.cn/blog_migrate/7ce9e0b97e64cc45e2f54db8518963a7.png)

### 最后重启Hive成功！！

![](https://i-blog.csdnimg.cn/blog_migrate/f832e0e639ca31c94192f1fe781afe49.png)