---
arturl_encode: "68747470733a:2f2f626c6f672e6373646e2e6e65742f4d61726b5f5f63616f:2f61727469636c652f64657461696c732f3734393431353339"
layout: post
title: "HDFS上传文件之WARN-hdfs.DFSClient-Caught-exception-java.lang.InterruptedException"
date: 2022-07-26 10:51:22 +0800
description: "HDFS上传文件时，可能会出现这样的警告：17/06/29 18:12:59 WARN hdfs.D"
keywords: "warn hdfs.dfsclient: caught exception"
categories: ['Hadoop', 'Error']
tags: ['无标签']
artid: "74941539"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=74941539
    alt: "HDFS上传文件之WARN-hdfs.DFSClient-Caught-exception-java.lang.InterruptedException"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=74941539
featuredImagePreview: https://bing.ee123.net/img/rand?artid=74941539
---

# HDFS上传文件之WARN hdfs.DFSClient: Caught exception java.lang.InterruptedException

HDFS上传文件时，可能会出现这样的警告：

*17/06/29 18:12:59 WARN hdfs.DFSClient: Caught exception
  
java.lang.InterruptedException
  


at java.lang.Object.wait(Native Method)
  


at java.lang.Thread.join(Thread.java:1245)
  


at java.lang.Thread.join(Thread.java:1319)
  


at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.closeResponder(DFSOutputStream.java:609)
  


at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.endBlock(DFSOutputStream.java:370)
  


at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:546)*

但是上传文件是成功的，在网上查了好久，说是hadoop的一个bug，可以忽略掉。