---
layout: post
title: "解决启动Hive出现Exception-in-thread-main-java.lang.RuntimeException-org.apache.hadoop.hive.ql.metadata"
date: 2022-12-28 17:41:53 +0800
description: "在启动Hive时出现如下错误：Logging initialized using configura"
keywords: 'exception in thread "main" java.lang.runtimeexception: org.apache.hadoop.hiv'
categories: ['未分类']
tags: ['无标签']
artid: "115558687"
image:
  path: https://api.vvhan.com/api/bing?rand=sj&artid=115558687
  alt: "解决启动Hive出现Exception-in-thread-main-java.lang.RuntimeException-org.apache.hadoop.hive.ql.metadata"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=115558687
featuredImagePreview: https://bing.ee123.net/img/rand?artid=115558687
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     解决：启动Hive出现Exception in thread “main“ java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="htmledit_views" id="content_views">
    <h2>
     在启动Hive时出现如下错误：
    </h2>
    <p>
     Logging initialized using configuration in jar:file:/usr/hive/apache-hive-2.1.1-bin/lib/hive-common-2.1.1.jar!/hive-log4j2.properties Async: true
     <br/>
     <strong>
      Exception in thread "main" java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
     </strong>
     <br/>
     at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:591)
     <br/>
     at org.apache.hadoop.hive.ql.session.SessionState.beginStart(SessionState.java:531)
     <br/>
     at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:705)
     <br/>
     at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:641)
     <br/>
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     <br/>
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     <br/>
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     <br/>
     at java.lang.reflect.Method.invoke(Method.java:498)
     <br/>
     at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
     <br/>
     at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
     <br/>
     <strong>
      Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
     </strong>
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.registerAllFunctionsOnce(Hive.java:226)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.&lt;init&gt;(Hive.java:366)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.create(Hive.java:310)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.getInternal(Hive.java:290)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.get(Hive.java:266)
     <br/>
     at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:558)
     <br/>
     ... 9 more
     <br/>
     <strong>
      Caused by: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
     </strong>
     <br/>
     at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1654)
     <br/>
     at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.&lt;init&gt;(RetryingMetaStoreClient.java:80)
     <br/>
     at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:130)
     <br/>
     at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.getProxy(RetryingMetaStoreClient.java:101)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.createMetaStoreClient(Hive.java:3367)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3406)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.getMSC(Hive.java:3386)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.getAllFunctions(Hive.java:3640)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:236)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.Hive.registerAllFunctionsOnce(Hive.java:221)
     <br/>
     ... 14 more
     <br/>
     Caused by: java.lang.reflect.InvocationTargetException
     <br/>
     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     <br/>
     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     <br/>
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     <br/>
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     <br/>
     at org.apache.hadoop.hive.metastore.MetaStoreUtils.newInstance(MetaStoreUtils.java:1652)
     <br/>
     ... 23 more
     <br/>
     Caused by: javax.jdo.JDOFatalInternalException: Error creating transactional connection factory
     <br/>
     NestedThrowables:
     <br/>
     java.lang.reflect.InvocationTargetException
     <br/>
     at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:671)
     <br/>
     at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:834)
     <br/>
     at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:338)
     <br/>
     at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:217)
     <br/>
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     <br/>
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     <br/>
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     <br/>
     at java.lang.reflect.Method.invoke(Method.java:498)
     <br/>
     at javax.jdo.JDOHelper$16.run(JDOHelper.java:1965)
     <br/>
     at java.security.AccessController.doPrivileged(Native Method)
     <br/>
     at javax.jdo.JDOHelper.invoke(JDOHelper.java:1960)
     <br/>
     at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1166)
     <br/>
     at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:808)
     <br/>
     at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:701)
     <br/>
     at org.apache.hadoop.hive.metastore.ObjectStore.getPMF(ObjectStore.java:515)
     <br/>
     at org.apache.hadoop.hive.metastore.ObjectStore.getPersistenceManager(ObjectStore.java:544)
     <br/>
     at org.apache.hadoop.hive.metastore.ObjectStore.initializeHelper(ObjectStore.java:399)
     <br/>
     at org.apache.hadoop.hive.metastore.ObjectStore.initialize(ObjectStore.java:336)
     <br/>
     at org.apache.hadoop.hive.metastore.ObjectStore.setConf(ObjectStore.java:297)
     <br/>
     at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:76)
     <br/>
     at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)
     <br/>
     at org.apache.hadoop.hive.metastore.RawStoreProxy.&lt;init&gt;(RawStoreProxy.java:58)
     <br/>
     at org.apache.hadoop.hive.metastore.RawStoreProxy.getProxy(RawStoreProxy.java:67)
     <br/>
     at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.newRawStore(HiveMetaStore.java:599)
     <br/>
     at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.getMS(HiveMetaStore.java:564)
     <br/>
     at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.createDefaultDB(HiveMetaStore.java:630)
     <br/>
     at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.init(HiveMetaStore.java:416)
     <br/>
     at org.apache.hadoop.hive.metastore.RetryingHMSHandler.&lt;init&gt;(RetryingHMSHandler.java:78)
     <br/>
     at org.apache.hadoop.hive.metastore.RetryingHMSHandler.getProxy(RetryingHMSHandler.java:84)
     <br/>
     at org.apache.hadoop.hive.metastore.HiveMetaStore.newRetryingHMSHandler(HiveMetaStore.java:6490)
     <br/>
     at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.&lt;init&gt;(HiveMetaStoreClient.java:238)
     <br/>
     at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.&lt;init&gt;(SessionHiveMetaStoreClient.java:70)
     <br/>
     ... 28 more
     <br/>
     Caused by: java.lang.reflect.InvocationTargetException
     <br/>
     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     <br/>
     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     <br/>
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     <br/>
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     <br/>
     at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
     <br/>
     at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:330)
     <br/>
     at org.datanucleus.store.AbstractStoreManager.registerConnectionFactory(AbstractStoreManager.java:203)
     <br/>
     at org.datanucleus.store.AbstractStoreManager.&lt;init&gt;(AbstractStoreManager.java:162)
     <br/>
     at org.datanucleus.store.rdbms.RDBMSStoreManager.&lt;init&gt;(RDBMSStoreManager.java:284)
     <br/>
     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     <br/>
     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     <br/>
     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     <br/>
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     <br/>
     at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
     <br/>
     at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:301)
     <br/>
     at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(NucleusContextHelper.java:133)
     <br/>
     at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:420)
     <br/>
     at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:821)
     <br/>
     ... 58 more
     <br/>
     Caused by: org.datanucleus.exceptions.NucleusException: Attempt to invoke the "BONECP" plugin to create a ConnectionPool gave an error : The specified datastore driver ("com.mysql.jdbc.Driver") was not found in the CLASSPATH. Please check your CLASSPATH specification, and the name of the driver.
     <br/>
     at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSources(ConnectionFactoryImpl.java:232)
     <br/>
     at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSources(ConnectionFactoryImpl.java:117)
     <br/>
     at org.datanucleus.store.rdbms.ConnectionFactoryImpl.&lt;init&gt;(ConnectionFactoryImpl.java:82)
     <br/>
     ... 76 more
     <br/>
     Caused by: org.datanucleus.store.rdbms.connectionpool.DatastoreDriverNotFoundException: The specified datastore driver ("com.mysql.jdbc.Driver") was not found in the CLASSPATH. Please check your CLASSPATH specification, and the name of the driver.
     <br/>
     at org.datanucleus.store.rdbms.connectionpool.AbstractConnectionPoolFactory.loadDriver(AbstractConnectionPoolFactory.java:58)
     <br/>
     at org.datanucleus.store.rdbms.connectionpool.BoneCPConnectionPoolFactory.createConnectionPool(BoneCPConnectionPoolFactory.java:54)
     <br/>
     at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSources(ConnectionFactoryImpl.java:213)
     <br/>
     ... 78 more
    </p>
    <h2>
     截图如下：
    </h2>
    <p>
     <img alt="" height="464" src="https://i-blog.csdnimg.cn/blog_migrate/7be88f5d29699e3509caa19156d635d9.png" width="936"/>
    </p>
    <h2>
     解决：
    </h2>
    <h3>
     在部署mysql的那个节点使用命令格式化mysql服务，如下：
    </h3>
    <blockquote>
     <p>
      <strong>
       schematool -dbType mysql -initSchema
      </strong>
     </p>
    </blockquote>
    <p>
     <img alt="" height="312" src="https://i-blog.csdnimg.cn/blog_migrate/7ce9e0b97e64cc45e2f54db8518963a7.png" width="947"/>
    </p>
    <h3>
     最后重启Hive成功！！
    </h3>
    <p>
     <img alt="" height="287" src="https://i-blog.csdnimg.cn/blog_migrate/f832e0e639ca31c94192f1fe781afe49.png" width="931"/>
    </p>
   </div>
  </div>
 </article>
 <p alt="68747470733a:2f2f626c6f672e6373646e2e6e65742f67756968756135352f:61727469636c652f64657461696c732f313135353538363837" class_="artid" style="display:none">
 </p>
</div>
