---
arturl_encode: "68747470733a2f2f626c6f672e:6373646e2e6e65742f77656978696e5f34303030303433302f:61727469636c652f64657461696c732f313134393130303630"
layout: post
title: "python-3.x版本的默认编码是_python-python3.X编码格式问题"
date: 2023-10-30 21:47:34 +08:00
description: "python3.X默认编码格式为UTF-8编码，因此对于汉字字符是可以自动识别的。但对于含有汉字字符"
keywords: "python3.x默认编码"
categories: ['未分类']
tags: ['X', 'Python']
artid: "114910060"
image:
  path: https://api.vvhan.com/api/bing?rand=sj&artid=114910060
  alt: "python-3.x版本的默认编码是_python-python3.X编码格式问题"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=114910060
featuredImagePreview: https://bing.ee123.net/img/rand?artid=114910060
---

# python 3.x版本的默认编码是_[python] python3.X编码格式问题

python3.X默认编码格式为UTF-8编码，因此对于汉字字符是可以自动识别的。但对于含有汉字字符的下列代码分别用纯txt文本、Geany编辑器、pycharm三种不同的方式编译执行时，唯独只有在pycharm中可以正确运行，其他两种均报错：

SyntaxError: Non-UTF-8 code starting with ‘\xb1‘ in file demo.txt on line 1, but

no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

name1 = "北京"name2=name1print(name1,name2)

name1= "南京"

print(name1,name2)

造成上述错误的原因是用纯txt文本和Geany编辑器编写的python程序的编码格式默认是ASCII和gbk，python3.x默认的编码格式是UTF-8，两者不一致。而pycharm中默认编码格式就是UTF-8格式。如下图将txt纯文本另存为UTF-8编码格式后，再执行程序就正常了。

![4a0d6b0c4818a9c5d557b1e6f4adaac9.png](https://i-blog.csdnimg.cn/blog_migrate/ccb8af6eab3ed556266a7e55601cb3a5.jpeg)

如下图对于Geany编辑器首选项中默认缺省文件格式为gbk编码格式，将其修改为UTF-8格式后，即可正确执行该代码。

![09b20ec439ffc1e36400c9d980a99147.png](https://i-blog.csdnimg.cn/blog_migrate/0bf288d0dd2a0878cc8761d516e09dac.jpeg)