---
arturl_encode: "6874747073:3a2f2f626c6f672e6373646e2e6e65742f726f6d6f6e31392f:61727469636c652f64657461696c732f313037373837393633"
layout: post
title: "unittest中单个测试用例,传参的问题"
date: 2023-04-01 03:17:06 +0800
description: "1、unittest中传参，从一个请求返回获取参数要在一个测试用例def 中完成，不能在下一个def"
keywords: "unittest变量调用"
categories: ['Python']
tags: ['无标签']
artid: "107787963"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=107787963
    alt: "unittest中单个测试用例,传参的问题"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=107787963
featuredImagePreview: https://bing.ee123.net/img/rand?artid=107787963
---

# unittest中单个测试用例，传参的问题

1、unittest中传参，从一个请求返回获取参数要在一个测试用例def 中完成，不能在下一个def中掉用

比如：

（1）变量
**recordid**
是从调用一个函数factor\_pre\_submit后获取到的，用于调用写一个函数时传入的参数

```
recordId = _a_03_factor_pre_submit.factor_pre_submit(order_data)
# # print(recordId)
time.sleep(1)
#根据初审生成的recordId，保理商预录入复核
factor_review = _a_03_factor_pre_submit.factor_pre_review(recordId)
# print(factor_review)
```

结果是能通的：

OK

![](https://i-blog.csdnimg.cn/blog_migrate/2f0d7f79eff85b1d26c85c41b6477bed.png)

Process finished with exit code 0
  
保理商预录入已初审
  
保理商预录入已复核

（2）在生成
**recordId**
后，在中间加一个def的测试函数，就会跑不通，显示
**recordId**
没定义

![](https://i-blog.csdnimg.cn/blog_migrate/e16abacedae1e543e08dba8e6ba3253a.png)