---
layout: post
title: "测试框架篇单元测试框架pytest4assert断言详解"
date: 2025-03-10 09:55:52 +0800
description: "就是对预期结果的断言。何为断言？简单来说就是实际结果和期望结果去对比，符合预期就测试pass，不符合预期那就测试 failed。断言内容就是你要的预期结果。断言包含对接口响应内容做断言、也包含对落DB的数据做断言。pytest可以让。"
keywords: "【测试框架篇】单元测试框架pytest（4）：assert断言详解"
categories: ['测试框架']
tags: ['单元测试', 'Pytest']
artid: "146144816"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=146144816
    alt: "测试框架篇单元测试框架pytest4assert断言详解"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=146144816
featuredImagePreview: https://bing.ee123.net/img/rand?artid=146144816
cover: https://bing.ee123.net/img/rand?artid=146144816
image: https://bing.ee123.net/img/rand?artid=146144816
img: https://bing.ee123.net/img/rand?artid=146144816
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     【测试框架篇】单元测试框架pytest（4）：assert断言详解
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="htmledit_views" id="content_views">
    <h2>
     <strong>
      一、前言
     </strong>
    </h2>
    <p>
     <strong>
      用例三要素之一
     </strong>
     就是对预期结果的断言。
    </p>
    <p>
     何为断言？简单来说就是实际结果和期望结果去对比，符合预期就测试pass，不符合预期那就测试 failed。断言内容就是你要的预期结果。断言包含对接口响应内容做断言、也包含对落DB的数据做断言。
    </p>
    <p>
     pytest可以让
     <a href="https://zhida.zhihu.com/search?content_id=172632527&amp;content_type=Article&amp;match_order=1&amp;q=%E5%BC%80%E5%8F%91%E8%80%85&amp;zhida_source=entity" rel="nofollow" title="开发者">
      开发者
     </a>
     使用Python断言来验证测试中的期望值。
    </p>
    <p>
     话不多说，我们来举个小例子熟悉一下，一般我们会在抛出异常之后输出一些提示信息，执行之后就方便查看是什么原因了。
    </p>
    <pre><code class="language-python"># 异常信息
def f():
    return 3
def test_function():
    a = f()
    assert a % 2 == 0, "判断 a 为偶数，当前 a 的值为：%s" % a</code></pre>
    <h3 id="tid-64QCFP">
     执行结果
    </h3>
    <p>
    </p>
    <p class="img-center">
     <a href="https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406130902312-172338387.png" rel="nofollow">
      <img alt="" height="462" src="https://i-blog.csdnimg.cn/img_convert/213319fed7c86a44a9c52857a7fceb6d.png" width="767"/>
     </a>
    </p>
    <p>
    </p>
    <h2 id="tid-3FMxyJ">
     二、常用断言
    </h2>
    <p>
     pytest 里面断言实际上就是 python 里面的 assert 断言方法，常用的有以下几种
    </p>
    <ul>
     <li>
      assert xx ：判断 xx 为真
     </li>
     <li>
      assert not xx ：判断 xx 不为真
     </li>
     <li>
      assert a in b ：判断 b 包含 a
     </li>
     <li>
      assert a == b ：判断 a 等于 b
     </li>
     <li>
      assert a != b ：判断 a 不等于 b
     </li>
    </ul>
    <h2 id="tid-QSTi4j">
     三、异常断言
    </h2>
    <p>
     可以使用 pytest.raises 作为上下文管理器，当抛出异常时可以获取到对应的异常实例
    </p>
    <pre><code class="language-python"># 断言异常
def test_zero_division():
    with pytest.raises(ZeroDivisionError):
        1 / 0</code></pre>
    <p>
     <strong>
      断言场景：
     </strong>
     断言它抛的异常是不是预期想要的
    </p>
    <p>
     <strong>
      代码执行：
     </strong>
     1/0
    </p>
    <p>
     <strong>
      预期结果：
     </strong>
     抛的异常是ZeroDivisionError: division by zero
    </p>
    <p>
     <strong>
      如何断言：
     </strong>
     通常是断言异常的 type 和 value 值了
    </p>
    <p>
     <strong>
      具体方式：
     </strong>
     这里 1/0 的异常类型是 ZeroDivisionError，异常的 value 值是 divisionby zero
    </p>
    <pre><code class="language-python">#详细断言异常
def test_zero_division_long():
    with pytest.raises(ZeroDivisionError) as excinfo:
        1 / 0

    # 断言异常类型 type
    assert excinfo.type == ZeroDivisionError
    # 断言异常 value 值
    assert "division by zero" in str(excinfo.value)</code></pre>
    <p>
     excinfo ：是一个异常信息实例
    </p>
    <p>
     <strong>
      主要属性：
     </strong>
     .type 、  .value 、 .traceback
    </p>
    <p>
     <strong>
      注意：
     </strong>
     断言 type 的时候，异常类型是不需要加引号的，断言 value值的时候需转 str
    </p>
    <p>
    </p>
    <h2 id="tid-yDFZAY">
     拓展一：match
    </h2>
    <p>
     可以将 match 关键字参数传递给上下文管理器，以测试正则表达式与异常的字符串表示形式是否匹配
    </p>
    <p>
     <strong>
      注意：
     </strong>
     这种方法只能断言value，不能断言type
    </p>
    <pre><code class="language-python"># 自定义消息
def test_zero_division_long():
    with pytest.raises(ZeroDivisionError, match=".*zero.*") as excinfo:
        1 / 0</code></pre>
    <p>
     该 match 方法的regexp参数与 re.search  函数匹配，因此在上面的示例中 match='zero' 也可以使用
    </p>
    <p>
    </p>
    <p class="img-center">
     <a href="https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406135355943-1838438116.png" rel="nofollow">
      <img alt="" height="261" src="https://i-blog.csdnimg.cn/img_convert/11a8284d2b73af32477bded112c6f552.png" width="586"/>
     </a>
    </p>
    <p>
    </p>
    <p class="img-center">
     <a href="https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406135407511-1382697695.png" rel="nofollow">
      <img alt="" height="70" src="https://i-blog.csdnimg.cn/img_convert/3bc9d4bee5cd88f4c6723961f125e42a.png" width="677"/>
     </a>
    </p>
    <h2 id="tid-WbJyH8">
     拓展二：检查断言装饰器
    </h2>
    <pre><code class="language-python"># 断言装饰器
@pytest.mark.xfail(raises=ZeroDivisionError)
def test_f():
    1 / 0</code></pre>
    <h3 id="tid-iZxc8c">
     执行结果
    </h3>
    <p>
    </p>
    <p class="img-center">
     <a href="https://img2020.cnblogs.com/blog/1896874/202004/1896874-20200406140623462-429848886.png" rel="nofollow">
      <img alt="" height="164" src="https://i-blog.csdnimg.cn/img_convert/b46b5ecee3c0bf298e61994555ffbe0c.png" width="674"/>
     </a>
    </p>
    <h3 id="tid-RsPJyc">
     知识点
    </h3>
    <ul>
     <li>
      代码抛出异常，但是和raises指定的异常类相匹配，所以不会断言失败
     </li>
     <li>
      它相当于一个
      <strong>
       检查异常装饰器
      </strong>
      <strong>
       ，功能：
      </strong>
      检查是否有异常，不确定是否有异常
     </li>
     <li>
      with pytest.raise(ZeroDivisionError)  对于故意测试异常代码的情况，使用可能会更好
     </li>
     <li>
      <code>
       而@pytest.mark.xfail(raises=ZeroDivisionError)
      </code>
      对于检查未修复的错误（即，可能会发生异常），使用检查断言可能会更好
     </li>
    </ul>
    <p>
    </p>
   </div>
  </div>
 </article>
 <p alt="68747470733a2f2f62:6c6f672e6373646e2e6e65742f6d305f33373133353631352f:61727469636c652f64657461696c732f313436313434383136" class_="artid" style="display:none">
 </p>
</div>


