---
layout: post
title: "thinkphp5.1-在fetch模版就超时"
date: 2025-03-06 18:55:01 +0800
description: "使用xdebug,追踪代码，发现走到D:\\temporary_files\\m40285_mini\\40285_mini\\thinkphp\\library\\think\\exception\\Handle.php，进入死循环，一直跳不出while循环，导致超时，并有错误信息。当被渲染模版不存在，请求不响应任何内容，过一会就timeout。将禁用函数去掉，即可抛出异常。"
keywords: "thinkphp5.1 在fetch模版就超时"
categories: ['未分类']
tags: ['Phpstorm', 'Php']
artid: "146077431"
image:
    path: https://api.vvhan.com/api/bing?rand=sj&artid=146077431
    alt: "thinkphp5.1-在fetch模版就超时"
render_with_liquid: false
featuredImage: https://bing.ee123.net/img/rand?artid=146077431
featuredImagePreview: https://bing.ee123.net/img/rand?artid=146077431
cover: https://bing.ee123.net/img/rand?artid=146077431
image: https://bing.ee123.net/img/rand?artid=146077431
img: https://bing.ee123.net/img/rand?artid=146077431
---

<div class="blog-content-box">
 <div class="article-header-box">
  <div class="article-header">
   <div class="article-title-box">
    <h1 class="title-article" id="articleContentId">
     thinkphp5.1 在fetch模版就超时
    </h1>
   </div>
  </div>
 </div>
 <article class="baidu_pl">
  <div class="article_content clearfix" id="article_content">
   <link href="../../assets/css/kdoc_html_views-1a98987dfd.css" rel="stylesheet"/>
   <link href="../../assets/css/ck_htmledit_views-704d5b9767.css" rel="stylesheet"/>
   <div class="markdown_views prism-atom-one-dark" id="content_views">
    <svg style="display: none;" xmlns="http://www.w3.org/2000/svg">
     <path d="M5,0 0,2.5 5,5z" id="raphael-marker-block" stroke-linecap="round" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
     </path>
    </svg>
    <h4>
     <a id="_0">
     </a>
     场景
    </h4>
    <p>
     当被渲染模版不存在，请求不响应任何内容，过一会就timeout
     <br/>
     <img alt="在这里插入图片描述" src="https://i-blog.csdnimg.cn/direct/5ed2d2f1cb344cc18b822bf21966dd92.png">
      <br/>
      <img alt="在这里插入图片描述" src="https://i-blog.csdnimg.cn/direct/d55eaa4856f54f6aa65c5a50eacd2b8b.png"/>
     </img>
    </p>
    <h4>
     <a id="_4">
     </a>
     排查过程
    </h4>
    <p>
     使用xdebug,追踪代码，发现走到D:\temporary_files\m40285_mini\40285_mini\thinkphp\library\think\exception\Handle.php，进入死循环，一直跳不出while循环，导致超时，并有错误信息
     <br/>
     <img alt="在这里插入图片描述" src="https://i-blog.csdnimg.cn/direct/64977d9e4ba24f70bbefd768b8a41458.png">
      <br/>
      <img alt="在这里插入图片描述" src="https://i-blog.csdnimg.cn/direct/3b4390915983462189e803f9b417b519.png"/>
     </img>
    </p>
    <h4>
     <a id="_8">
     </a>
     解决
    </h4>
    <p>
     将禁用函数去掉，即可抛出异常
     <br/>
     <img alt="在这里插入图片描述" src="https://i-blog.csdnimg.cn/direct/d81975ab11484915a841c6152db6a1ea.png">
      <br/>
      <img alt="在这里插入图片描述" src="https://i-blog.csdnimg.cn/direct/98bcaefcca86481a952541696c93a4ee.png"/>
     </img>
    </p>
   </div>
   <link href="../../assets/css/markdown_views-a5d25dd831.css" rel="stylesheet"/>
   <link href="../../assets/css/style-e504d6a974.css" rel="stylesheet"/>
  </div>
 </article>
 <p alt="68747470733a2f2f62:6c6f672e6373646e2e6e65742f71715f33363935373730312f:61727469636c652f64657461696c732f313436303737343331" class_="artid" style="display:none">
 </p>
</div>


